= コンポーネント (Components)
:page-partial:

Decidimの構成要素は、様々な参加型スペースやサブスペース（プロセスの段階、身体の作業グループなど）のために活性化され、設定される基本的な参加型メカニズムです。

Decidim’s components are basic participatory mechanisms that are activated and configured for the various participatory spaces or subspaces (stages of a process, the work groups of a body, etc.).

== 提案 (Proposals)

提案はDecidimの最も重要な要素です。提案とは、戦略計画、規制、投資計画、法律の変更、またはその他の最低限の意思決定単位の要素として定義することができます。提案は、プラットフォームを管理する組織（地方自治体など）、登録された参加者、議論や集団的な審議の結果として会議から発生する場合もあれば、集会や団体、プラットフォームに登録された組織によって作成される場合もあります。また、 **直接または共同で作成されたもの** であってもよいですし、 *修正* の対象となるものであってもよいです。

Proposals are Decidim's most important component. Proposals can be defined as any element of a strategic plan, a regulation, an investment plan, a change in legislation or any other minimum decision unit. Proposals may be made by any of the following *types of creators*: by the very organisation managing the platform (e.g. a local authority); by registered participants; they may originate from a meeting as a result of a discussion or collective deliberation or may be generated by an assembly or body or by an organisation registered with the platform. They may also **be created directly or collaboratively **and be subject to *amends*.

提案は、1人または複数の著者、タイトル、テキストの内容、カテゴリによって定義されます。提案書には、*画像* 、 *地理的位置* 、 *添付ファイル* も含めることができます。

Proposals are defined by one or more authors, a title, a text content and a category. They may also include *images*, **geo-location **and *accompanying files*.

一旦公開された課題は、(誰かがそのようにラベルを付け、モデレーティングの理由を定義した場合)  *モデレート* されることがあり、また、著者自身が *取り下げられる* こともあります。

Once a proposal has been published it may be *moderated* (if someone labels it as such and defines the reason for moderating) and it can also be *withdrawn* by author/s themselves.

*管理* パネルでの提案は、様々な基準に基づいて *順序付け* ができ、内部的にコメントをつけること(一般の人には見られません)ができます。またJSONまたはCSVフォーマット(表計算ソフトと互換性があります)でダウンロードすることもできますし、他のスペースに *再カテゴライズ* したり *移動* したりすることもできます。さらに、提案は、*承認* 、 *却下* 、*評価中* の状態で保存することができます。

Proposals in the *administration* panel can *be ordered* under various criteria, can be commented on internally (without these observations being seen by the public), can be *downloaded* in JSON or CSV format (compatible with spreadsheet software), can be *recategorised* or *moved* to different spaces. In addition, proposals may be *accepted*, *rejected* or kept in an *evaluating* state.

提案に関連するその他の機能としては、以下のものがあります:

Other features associated with proposals include:

* *バージョン管理* : 提案に加えられたすべての変更の記録を保持したり、提案の完全性を検証するためのコード生成が可能になります。 *Version control*: this makes it possible to keep a record of all the changes made to a proposal, as well as code-generation to verify the proposal’s integrity.
* *類似性の検出*: 新しい提案を作成する人は、以前にプラットフォーム上で作成された類似した提案を見つけることができ、重複を避けることができます。 *Detecting similarities*: This allows anyone making a new proposal to find similar ones previously made on the platform, thereby avoiding duplications.
* *提案間の接続*: 作成された提案は、コメント欄のリンクを使用して互いに接続することができ、関連する提案をカードとして表示し、新しい接続の存在を通知します。 *Connections between proposals*: proposals made can be connected to one another using links in the comments section, showing related proposals as cards and giving notifications on the existence of a new connection.
* *提案のサポート*：参加者が提案をサポートすることができます。 *Support proposal*: participants can provide support for proposals.
* *提案のエンドース*: 参加者や団体が提案を支持することができます。 *Endorsement of proposals*: participants and collectives can endorse proposals and such public endorsement will be shown within the proposal, followers of the endorsers will be notified that the followed endorsed the proposal.
* *提案の修正と撤回*: 提案の作者は、支援ステージが開始される前に提案を修正したり、撤回したりすることができます。  *Modification and withdrawal of proposals*: a proposal’s author may modify and/or withdraw it before the support stage opens.
* *修正*: 参加者は誰でも提案のテキストを編集することができ、修正モードでサブ提案が(Github の Pull Request として)作成されます。このサブプロポーザルは支持とサポートを集めることができます。その上、提案の作成者は修正(またはサブ提案)を承認するか拒否するかを決めることができます。サブプロポーザルが却下された場合、その作成者はそれを公式のプロポーザルに変換することができます。 *Amends*: any participant can edit a proposal’s text and a sub-proposal will be created in amendment mode (as Pull Request in Github). This sub-proposal may gather endorsements and supports. Besides, the proposal’s author may accept or reject the amendment (or sub-proposal). Where a sub-proposal is rejected, its author may convert it into an official proposal.
* *提案書作成ウィザード*: 提案書が作成されている間、参加者は、提案書が公開される前に、異なるステップに分けられたプロセスを、文脈に沿ったヘルプとプレビューを使って、参加者に同行します。 *Proposal creation wizard*: While a proposal is being created, the participant is accompanied through the process, which is divided into different steps, with contextual help and previews before the proposal is published.
* *提案書のための共同ドラフト*: Decidimは、プロポーザルの上でのコラボレーションと共創を可能にします。以下の機能を搭載しています。 *Collaborative draft for proposals*: Decidim permits collaboration and co-creation over proposals. It incorporates the following features:
** 多数の参加者とラフドラフトを共同で作成することができます。 Creating rough drafts with numerous authors.
** 共同下書きのリスト The listing of collaborative drafts
** 下書きのコメント Comments in drafts
** 他の協力者に助けを求め、協力を受け入れられます Asking for help from and accepting the help of other collaborators


== 参加型テキスト (Participatory texts)

参加型テキストとは、完全なテキストを持つ文書を構成する提案の順序立てられた集合体と定義されています。テキストへの参加は、それを形成する提案との相互作用から生じます。このコンポーネントでは、基本的に以下の3つの操作が可能です:

Participatory texts are defined as an ordered collection of proposals that make up a document with complete text. Participation in the text stems from interaction with the proposals that form it. This component basically allows three operations:

* *テキスト文書を箇条書きのプロポーザルに分解する*: ODT、XDOC、MarkDown、HTML形式の文書が利用できます。テキストがセクションやサブセクションで構成されている場合は、下位レベルのサブセクションから順にプロポーザルが作成され、テキストが構成されていない場合は、テキストの各段落ごとにプロポーザルが作成されます。このインターフェイスでは、提案書の再編集、マージ、分離、タイトルの付与などを行うことができます。 *Breaking down a text document into ordered proposals* from a document in ODT, XDOC, MarkDown and HTML formats. If the text is structured in sections and subsections, ordered proposals will be created from the lower level subsection; if the text is not structured, a proposal will be created for each paragraph of text. The interface allows proposals to be re-edited, merged, separated, given titles, etc.
* *統合されたテキストとしての提案の作成*: 一連の提案に基づいて、これらを順番に並べて、統一されたダウンロード可能なテキストを生成することができます。 *Composition of proposals in a unified text*: based on a series of proposals, these may be ordered and generate a unified and downloadable text.
* *提案書で構成されたドキュメントの表示と対話*: 提案書の集合体が統一されたテキストとして表示され、修正や余白にコメントを追加することができます。 *Viewing and interacting* with documents composed of proposals: A collection of proposals will be shown as a unified text and may be amended or comments can be added in the margin.

== 結果 (Results)

結果とは、Decidimで行われた決定の結果となった提案(または提案の修正)のことで、直接(投票システムを適用した結果)であっても、会議、集会、またはプラットフォームの管理を通じて決定領域を担当する専門家や政治チームによってもたらされたものであっても、どちらでも構いません。

Results are proposals (or amendments to proposals) which have ended up being the result of a decision taken in Decidim, whether directly (as a consequence of applying a voting system) or brought about by meetings, assemblies or the expert or political team in charge of a decision area through the platform’s management.

結果コンポーネントでは、提案されたすべての提案に対して*公式な回答*を管理することができます: 提案を拒否または承認した理由と、提案が承認された結果が表示されます。

The results component allows *official responses* to be managed for all the proposals made: with the reason for rejecting or accepting the proposal and the result in which the proposal has been accepted.

結果は、結果に組み込まれた提案のトレーサビリティ*や、それらの提案が議論され、議論された会議や作成された会議（会議に出席した人たち）、受け取った承認に関するメタデータを収集します。

Results collect *metadata on the traceability* of the proposals incorporated into the result, as well as the meetings where they were discussed and debated or created (by those attending these meetings) and the endorsements received.

== 説明責任: 結果のモニタリング (Accountability: monitoring results)

結果モニタリングコンポーネントでは、 *結果をプロジェクトに変換* したり、プロジェクトやサブプロジェクトに分解したりすることができます。これらの各プロジェクトは、さらに詳細に記述することができ、実装率0%から100%までの範囲で *実装状況を定義* することができます。モニタリングコンポーネントはまた、プラットフォームを訪れた人が、成果やプロジェクトの *実施レベルを見る* ことができます。結果、プロジェクト、ステータスは、CVSを通して、あるいは管理者インターフェースで手動で更新することができます。

The result-monitoring component enables *results to be turned into projects* or allows them to be broken down into projects or sub-projects. Each of these projects can be described in further detail and allows *the implementation status to be defined*, in sections which range from 0% implementation to 100%. The monitoring component also enables people visiting the platform to *view the level of implementation* (comprehensive, by category and/or subcategory), of the results and projects. Results, projects and statuses can be updated through a CVS, or manually by the administration interface.

== 支援/投票と承認 (Support/votes and endorsements)

参加者は提案を支持することができます。そのような支持は、投票、署名、支持、または政治的意志そのものに従った肯定的な合意を示すその他の形式で解釈することができます。

Participants can endorse proposals. Such endorsements can be interpreted as votes, signatures, endorsements or in any other format that demonstrates a positive agreement in accordance with the political will itself.

Decidimには、このための *支援/投票/管理システム* がいくつもあります。最も単純な方法は、支持を有効にすることで、参加者は、投票できる提案の数に制限を設けることなく、希望する各提案に対して単一の支持を発行することができます。また、投票数を制限することもできます (例: 参加者一人につき10票)。

There are *several support/voting and management systems* for this in Decidim. The simplest way is by activating endorsements, so that participants can issue a single endorsement for each proposal they wish, without any limit to the number of proposals that can be voted for. Alternatively, the number of votes can be limited (e.g. 10 per participant).

管理パネルから、投票期間中または投票期間終了後の *投票結果の表示設定* を行うことができます。

From the administration panel it is possible to configure the *display settings for the voting results* either during or solely after the voting period.

*参加型予算の投票に使用される特別なフォーム* があり、参加者は提案されたプロジェクトの中から予算に相当する金額を「支出」して投票することができます。ここでは、選択されたプロジェクトの累積支出額によって投票数が制限される。

There is a *special form used to vote for participatory budgets* which allows participants to vote by "spending" an amount equivalent to the budget in question among the proposed projects. The number of votes is limited here by the selected projects’ accumulated spending amount.

== コメント (Comments)

コメントは、一般的に別のコンポーネント（提案、議論と討論、結果、会議など）に関連付けられた特別なコンポーネントであり、問題や提案に関する審議プロセスを可能にします。

Comments are a special component generally associated with another component (proposals, discussions and debates, results, meetings etc.) to enable a deliberative process on an issue or proposal.

Decidimのコメントシステムは、審議を奨励するために設計されています。議論の主題に関する第一レベルのコメントは、以下のように分類することができます: *賛成、反対、中立*。コメントはサブセクションのコメントスレッドに *埋め込む* ことができ 、*投票する* ことができます。Decidimでは、*意見を賛成、反対、時系列順、賛成票数順にランク付け* することができます。

Decidim’s comments system has been designed to encourage deliberation. First-level comments, with respect to the discussion's subject matter, can be classed as: *In favour, against or neutral*. Comments can be *embedded* in subsection commentary threads and *voted on*. Decidim allows *observations to be ranked* by those in favour or against, in chronological order and by number of votes in favour.

== 参考ページ (Informative pages)

参加型スペースのインナーメニューに表示されるタイトルとhtmlコンテンツのページです。ここに画像や動画、リッチテキストを埋め込むことができます。

This is a page with html content and a title that appears in the inner menu of the participatory spaces. It is possible to embed images, videos and rich text here.

== 議論と討論 (Discussions and debates)

管理者や参加者が設定した質問や具体的な問題について、議論や討論を行うことができます。

Discussions and debates can be opened on questions and specific issues established by administrators or participants.

== 調査 (Surveys)

調査コンポーネントでは、様々な参加型空間で実施できるアンケートの設計・実施や結果のマッピング、加工・表示が可能です。

The surveys component allows to design and conduct surveys and to mappe out
the results, processed and displayed for surveys that can be carried out in various participatory spaces.

* *アンケート設定ツール*: 管理者は、質問と回答の作成（オープン、テストタイプ、複数選択など）やアンケートの起動、回答をCSV形式でダウンロードすることができます。 *Survey configuration tool*: allows administrators to create questions and answers (open, test types, multiple selection etc.) and launch the survey, as well as download the responses in CSV format.
* *参加者向けアンケートインターフェース*：参加者がアンケートの質問に回答することができます *Survey interface for participants*: allows participants to respond to survey questions.

== 対面でのミーティング (In-person meetings)

このコンポーネントを使用すると、ユーザーは会議の開催、*地理的位置情報を含むカレンダーへの追加* 、 *議事録のアップロード* 、 *討論* 、会議に関連した *提案書の作成* （提案に対する集団的な支持の種類を示す）、 *参加者数* の記録、会議の *写真* のアップロード、およびスペース内での会議の *分類* が可能になります。

This component enables users to convene meetings, *add them to a calendar with geo-location*, upload *meeting minutes*, *debate*, create *proposals associated* with meetings (stating the type of collective endorsement for the proposal), record the *number* of participants, upload *photos* of the meeting and *categorise* the meeting within a space.

*会議の設定* には、以下の *基本フィールド* が含まれています: タイトル、説明、住所、場所、場所のヒント、開始時間と終了時間、範囲、カテゴリ、最大収容人数。

The configuration *settings* for meetings include the following *basic fields*: Title; description; address; location; Location hints; start and end time; scope; category and maximum seating capacity.

また、以下の *高度なフィールド* も含まれます: 性質（公開、オープン、クローズ）、主催者グループ、和解空間の存在、機能的多様性を持つ人々への適応、同時通訳の存在、会議の種類（情報提供、創造、審議、意思決定、評価、説明など）。

It also includes the following *advanced fields*: nature (public, open, closed); organiser group; existence of reconciliation space; adaptation to people with functional diversity; existence of simultaneous translation; type of meeting (informative, creative, deliberative, decision-making, evaluative, account giving, etc.).

参加型スペース（特定のプロセスや集会）に関連する会議は、*マップ* 上に表示され、*日付やカテゴリで順番に並べる* ことができます。また、すべての会議は *カレンダーモード* で表示することができ、携帯電話のカレンダーや他のアプリにエクスポートすることも可能です。

Meetings relating to a participatory space (a specific process or an assembly) can be shown on a *map* and be *ordered by date or category*. Besides, all the meetings can be shown in *calendar mode*, with the possibility of exporting them to a mobile phone calendar or other apps.

会議コンポーネントの高度な機能の一部は以下の通りです。

Some of the meeting component’s advanced features include:

* *登録・出席システム* *Registration and attendance system*:
** これにより、*登録の種類* の管理(オープンと自動、クローズドと特定のタイプの参加者のみアクセス可能など)、参加者が利用できる **場所の数** の設定、場所の予約、 *手動登録* の実行、 *招待状* の送信、会議に参加するために必要な *条件* の定義(例：画像の権利解放)、参加者の出席登録などが可能になります。 This allows to manage the *type of registration* (open and automatic, closed and accessible only to certain types of participants, etc.), to establish the **number of places **available for attendees, to reserve a place, to do *manual registrations*, sent out *Invitations*, to define the *conditions* that need to be accepted in order to be able to attend the meeting (e.g. image rights release), and *registering the attendance* of participants.
** 参加者は、会議への *参加登録* 、 *家族向けサービス* （プレイルーム、託児スペース）の申し込み、会議参加のための *認定コード* を取得することができます。 It allows participants *to register* for a meeting, request *a family reconciliation service* (playroom, childcare space) and to obtain an *accreditation code* for attending at a meeting.
** 会議に参加登録された方は、会議の評価やコメントなどができる *特別なアクセス権* が与えられます。 Those registered who have attended a meeting will have *special access* enabling them to evaluate the meeting or make comments, etc.
** 参加者や管理者には、登録期間の空き状況、残席数、会議のリマインダー、議事録の発行などの *通知* を受けることができます。 Participants or administrators will be able to receive *notifications* on registration-period openings, the number of places remaining for registrations, reminders of meetings, and the publication of minutes.
* *議題の管理*: 会議の期間を定義し、議題の項目や小項目、タイトル、内容、予定期間を作成することができます。参加者は議題項目を提案することができます。 *Managing agendas*: allows to define the duration of meetings, to create agenda’s items and sub-items, title, content, and estimated duration. Participants can propose agenda items.
* *議事録の作成、公開、検証* のためのシステム [IMPORTANT NOTICE: これは現在別の方法で実装されています]: System for *drafting, publishing and validating meeting minutes* [IMPORTANT NOTE:This is currently implemented differently]:
** 議事録は、ビデオ、音声、テキスト形式でアップロードできます。 Minutes can be uploaded in video, audio or text format.
** テキストモードの議事録は、Decidimに統合された *共同ライティングボード* に関連付けられています。 Minutes in text mode are associated with a *collaborative writing board* integrated into Decidim.
** *4つの準備段階* を経て作成される議事録:  1.会議中の共同執筆、2.議事録の公式草稿の作成、3.草稿修正段階、4.議事録の公開と最終確認。 Minutes go through 4 *stages of preparation*: 1. Collaborative writing during the meeting; 2. Preparing the official draft of the minutes; 3. Draft-amendment stage; 4. Publication and final validation of the minutes.
**  議事録は、コメント機能を使ってコメントすることができます。 Minutes can be *commented on* using the comments component.
** *議事録に付随する文書* を追加することもできます。 *Accompanying documents* may also be added to the minutes.
* *自動会議開催*: 検証済みの参加者は、一定数の他の参加者のサポートを得て、プラットフォームを介して直接会議を開催することができます。 *Auto-convening*: verified participants will be able to convene meetings directly through the platform , with support from a certain number of other participants, the meeting will be publicly activated and convening participants will have access to the administration panel [IMPORTANT: not implemented yet]
* *ミーティングの表示とエクスポート*: ミーティングは、マップモード（スペースまたはプラットフォーム上の一般的な）またはカレンダーモードで表示することができ、アジェンダやカレンダーマネージャ（iCalendar形式）にエクスポートすることができます。 *Displaying and exporting meetings*: meetings can be displayed in map mode (for spaces or generally on the platform) or in calendar mode, and can be exported to agenda and calendar managers (in iCalendar format).

== カンファレンス (Conferences)

カンファレンスとは、いくつかの特定の機能（インタラクティブでダウンロード可能なプログラム、登録システム、出席証明書や卒業証書を生成するシステム）を持つ一連の会議と定義されています。

Conferences are defined as a series of meetings having several specific features (interactive and downloadable programme, registration system, system for generating certificates of attendance and/or diplomas).

Decidimには設定とカンファレンスページ生成機能があり，参加型プロセスや他の参加型空間に関連した *会議を開催するための内部ウェブサイト* を作成することができます。

Decidim has a configuration and conference-page generator, which enables the creation of an *internal website for holding conferences* relating to a participatory process or another participatory space.

設定項目は以下の通りです:

Configuration settings include:

* イベントの*インタラクティブなプログラム*を生成するオプション(ゲストスピーカーがいる場合は、名前、役職、組織、小さな経歴、他のウェブサイトへのリンクが含まれます)。 The option to generate an *interactive programme* on the event (where there are guest speakers, it will include their name, position, organisation, a small biography and links to other websites).
* *招待状* をメールで送ることができます。 Email *invitations*.
* 管理者が確認できるサポートパネルを使って、ご希望の方のために *ディプロマの自動作成* を行います。 *Automatic diploma creation* for those who request it, through a support panel that an administrator can verify.
* プログラムや資料の中にあるイベントのビデオや資料へのリンク。 Links to the event *video and materials* platforms in the programme and documents.
* イベントをカバーするデジタルメディアのウェブサイトへの自動リンク。 Automatic links to digital-media websites covering the event.
* *ソーシャルネットワーク* を通じてイベントをフォローする機能（例: Twitterフィードの組み込み）。 The ability to following events through *social networks* (e.g. by incorporating a Twitter feed).

== ブログ (Blogs)

ブログは、*ニュースアイテム* を作成し、時系列的に表示するためのコンポーネントです。ブログエントリーは、もう一つのタイプのコンテンツであり、参加型スペースと関連づける必要があります。ブログエントリーは、プラットフォームのコンテンツの分類システムに関連しています。ブログエントリーに *関連付けられたコメント* は、上記の通り、プラットフォームの他のコメントと同じように扱われます。

Blogs are a component that allow *news items* to be created and displayed chronologically. Blog entries are another type of content and have to be associated with a participatory space. Blog entries relate to the classification system of the platform’s content. *Comments associated* with blog entries will be treated like the platform’s other comments, as described above.

== ニュースレター (Newsletter)

Decidimには、利用規約に同意したプラットフォームに登録した人全員に *ニュースレター* （メール）を送信する機能があります。パーソナライズされた電子メールは、デフォルトではユーザーが選択した言語でユーザーの名前に直接送信されます。

Decidim has a function which enables a user to send a *newsletter* (email) to everyone registered with the platform who has agreed, under the terms and conditions of use, to receiving this information newsletter email. Personalised emails are sent out addressed directly to the name of the user in the language chosen by the user by default.

参加者は、メールに記載されたリンクをクリックすることで、自動的に直接、メールの *配信停止* を行うことができ、また、ニュースレターによって生成された *訪問数を追跡* することも可能です。

Participants will automatically and directly be able to *unsubscribe* through the email itself by clicking on a link in it and it will also be possible to *track the number of visits* generated by the newsletter.

== 検索エンジン (Search engine)

*検索エンジン* では、参加者は、特定の参加型プロセスやその構成要素(提案、結果など)の中で、高度な検索を行うことで、プラットフォームのインデックス化可能な全てのコンテンツを、一般的にも具体的にも検索することができます。

*The search engine* allows participants to perform searches across all of the platform’s indexable content, both generally and specifically, by searching within a specific participatory process or inside its components (proposals, results, etc.), through advanced searches.

*検索結果から閲覧・フィルタリングが可能なページ* は、その種類に応じてコンテンツを表示し、定義された優先度で順番に表示します(例: アセンブリ内で見つけた用語を最初に表示し、後に参加型プロセスを表示する)。

*Pages that can be browsed and filtered from search results* show contents according to their type and ordered by the priority they have been defined under (e.g. Showing first the terms found inside assemblies and later the participatory processes).

== 並べ替え (Sortitions)

このコンポーネントは、ランダム性の保証を最大化し、管理者による結果の操作を回避するために、提案の集合（または集合内の提案のカテゴリ）の中から提案の数をランダムに選択することを可能にします。

This component makes possible to select randomly a number of proposals among a set of proposals (or a category of proposals within a set) maximizing guarantees of randomness and avoiding manipulation of results by the administrator.
