= 背景 (Background)

:experimental:
:icons: font
:page-partial:
:source-highlighter: highlightjs

== ネットワーク社会への市民参加 (Citizen participation in the Network Society)

ネットワーク社会への移行。情報通信技術（以下、ICT）とそれに関連した実践は、社会的・政治的景観に不可逆的な変化をもたらしています。小さな自治会から、最も集中的な選挙運動、近所の組織や社会運動から欧州連合まで、政治的関係はデジタル機器やテクノロジーの使用によってますます決定されています。民主的な参加と集団行動の未来は、デジタル・プラットフォームとハイブリッド・プロセスの開発を通じて、伝統的な慣行を刷新し、デジタルなものと組み合わせることになるように思わています(Fuchs, 2007)。

Becoming a network(ed) society. Information and communication technologies (henceforth, ICTs) and their associated practices are bringing about irreversible changes to the social and political landscape. From the smallest residents’ association to the most intensive electoral campaign, from a neighbourhood organisation or social movement to the European Union, political relations are being increasingly determined by the use of digital devices and technologies. It seems that the future of democratic participation and collective action will be through the development of digital platforms and hybrid processes, which renovate traditional practices and combine them with digital ones (Fuchs, 2007).

この移行は、ここ数十年の代表制の衰退と一致しています（Norris, 1999; Pharr & Putnam, 2000; Tormey, 2015）が、民主主義そのものの正当性と感覚への疑問に貢献しています。いくつかの著者は、グローバリゼーションから市民の不満と離反に向かう代表機関の権力と意味の空虚化を指すために「ポスト代表」という用語を使用しています（Brito Vieira and Runciman, 2008; Keane, 2009; Rosanvallon , 2011; Tormey, 2015）。参加を促進するための様々な試みは、これらの傾向を逆転させるには不十分であることが証明されています(Keane, 2011; Tormey, 2015)。

This transition coincides with the decline of representative systems over the last few decades (Norris, 1999; Pharr & Putnam, 2000; Tormey, 2015), which has contributed to the questioning of the legitimacy and sense of democracy itself, reduced and often identified with this system (Crouch, 2004; Keane, 2009; Streeck, 2016). Several authors have used the terms “post-representation" to refer to the emptying of power and meaning of the representative institutions that go from globalisation to disaffection and divestment of citizens (Brito Vieira and Runciman, 2008; Keane, 2009; Rosanvallon , 2011; Tormey, 2015). The various attempts to boost participation have proved unequal to the task of reversing these trends (Keane, 2011; Tormey, 2015).

長く続いているこの政治危機は、2008年の金融・経済危機を背景にしており、それ以前の危機に直結しています。それでも、何百万人もの人々が危機に直面して動員され、要求するだけでなく、真の民主主義を実験し、構築することを意図していました。ここでの重要な展開は、15Mネットワーク運動である。1980年代と1990年代に金融の流れとグローバリゼーションを加速させるために利用された情報通信技術（カステルズ、1996年）が、民主主義的な実験だけでなく、政策の再利用を多様に行うための重要な空間と装置となったのは、技術的なハイパーメディエーションの文脈の中でのことです（マルティネット・ロスら、2015年）。

This long-running political crisis comes on the back of the financial and economic crisis of 2008, and is directly linked to this earlier crisis. Even so, millions of people mobilised in the face of the crisis, intent not only on demanding but also on experimenting and building a real democracy. The key development here was the 15M network-movement. It is in the context of technological hypermediation that information and communication technologies, used in the 1980s and 1990s to accelerate financial flows and globalisation (Castells, 1996), became crucial spaces and devices for a multitudinous re-appropriation of policy, as well as democratic experimentation (Martinet Ros et al., 2015).

数々の成功と失敗の4年間を経て、2015年5月には、バルセロナを含むスペインの主要都市で新たな政治的市民イニシアチブがなんとか政権を握ることができた。この点で、彼らはアイスランドのような国々の潮流に乗っていたが、経済危機によって市民が制度を再利用し、ICTの強烈で創造的な利用に基づいた肥沃な民主主義的イノベーションの時期を迎えていました。

After four years of numerous successes and failures, new political citizen initiatives in May 2015 managed to take power in Spain’s main cities, including Barcelona. In this respect they were riding on the tide of countries such as Iceland, where the economic crisis had led to a period of citizen re-appropriation of the institutions and fertile democratic innovation, based on an intense and creative use of ICTs.

15M以降、参加型・審議型民主主義の新しい形を導入することを目的とした実験（Barber, 1984; Habermas, 1994, 1996; Della Porta 2013）のほとんどは、技術的に媒介されてきました。アイスランド（フィンランドなど）の事例からもわかるように、市民動員とエンパワーメントの民主化プロセスは、その豊かさと能力を最大限に発揮するために、テクノポリティクス（Rodotà 1997; Martinet Ros et al., 2015）による調整を必要とします。テクノポリティクスは、政治とテクノロジーの共同開発と共同生産と同様に、テクノロジーの政治化と政治のテクノロジー的再集合から生じます。テクノポリティクスへの参加と審議の形態としては、デジタルと対面での実践、空間、プロセスが互いに接続し、相互にフィードバックし、多層的な次元を獲得しています。これらの参加型デバイスは、都市の共通の政府に「参加」するプレイヤーの数、多様性、平等性を高め、それが行われる地域、形態、期間を拡大し、豊かにし、現代の都市生活の複雑さに対応できる集合的な知性（Levy, 1997）を高めることを目的としています。テクノポリティクスは、デジタルを媒介とした参加をめぐるテクノセントリックでテクノオプティミスティックなナラティブからの解放から始まる、「デジタル民主主義」（Hindman, 2008）と呼ばれてきたものの数々の限界に取り組む必要があります。

Since 15M, most of the experiments aimed at introducing new forms of participatory and deliberative democracy (Barber, 1984; Habermas, 1994, 1996; Della Porta 2013) have been technologically mediated. As can be seen from the case of Iceland (as well as others, such as Finland), the democratising processes of citizen mobilisation and empowerment require technopolitical coordination (Rodotà 1997; Martinet Ros et al., 2015) to achieve their maximum richness and capacity. Technopolitics stems from the politicisation of technologies and technological re-assemblage of politics as well as the co-development and co-production of politics and technologies. As for forms of technopolitical participation and deliberation, digital and face-to-face practices, spaces and processes connect to and feed back from one another, acquiring a multi-layered dimension. These participatory devices are geared towards increasing the number, variety and parity of players that "take part" in the city’s common government, expanding and enriching the areas, forms and periods in which it takes place and helping to boost a collective intelligence (Levy, 1997) capable of taking on the complexity of contemporary urban life. Technopolitics needs to tackle the numerous limits of what has been called “digital democracy" (Hindman, 2008) starting by freeing itself from the technocentric and technooptimistic narratives around digitally mediated participation.

新しい参加型のプロセスは、機会に満ち、リスクを伴う文脈の中で構築されています。バルセロナ市のために策定された2015年の政府プログラムと2016-2019年の自治体アクションプログラム（PAM）は、参加、より具体的にはイノベーションと新しい民主的な参加モデルの開発を中心に据えています。何千人もの人々が参加したPAMは、民主主義システムとその参加型メカニズムの徹底的な再設計を求める明確な社会的要求を満たしています。しかし、これは次のような状況の中で起こっています。a) 大きな政治的、経済的、社会的に排除された人口部門; b) 経済危機的状況の結果、参加へのアクセスがますます困難になっている; c) 代表的な民主主義システムと公的機関の正当性と操作性に対する危機; d) 民間企業のインフラとサービスへの巨大な技術的依存; e) 直接民主主義、社会的独立性、領土主権に不利な法的、政治的文脈; f) 社会行動データを分析する技術や、大規模な技術企業とデジタル的に調整されたサービスが持つモデルを通して社会的複雑性を理解する上での、ひどい制度的不利.

New participatory processes are being built within a context full of opportunities and fraught with risks. The 2015 government programme and Municipal Action Programme (PAM) for 2016-2019 drawn up for the city of Barcelona gives centre stage to participation and, more specifically, innovation and the development of new democratic participatory models. PAM, ​​the development of which involved thousands of people, meets a clear social demand that calls for ​​a thorough redesign of the democratic system and its participatory mechanisms. This, however, is occurring in a context defined by: a) large politically, economically and socially excluded population sectors; b) increasing difficulty accessing participation as a result of the economic-crisis situation; c) a crisis over the legitimacy and operability of the representative democratic system and public authorities; d) an enormous technological dependency on private corporate infrastructures and services; e) a legal and political context adverse to direct democracy, social independence and territorial sovereignty; f) an abysmal institutional disadvantage in understanding social complexities through techniques analysing social-behaviour data and models that big technological companies and digitally coordinated services possess.

[[h.2et92p0]]
== 民主主義のためのデータ制御とデジタルインフラ (Data Control and digital infrastructures for democracy)

情報資本主義（Castells, 1996）、いわゆる「データ資本主義」（Lohr, 2015; Morozov, 2015）、あるいは「監視資本主義」（Zuboff, 2015）の新しい構成の文脈において、民主主義の新しいデジタル・インフラは、プライバシーや技術的主権などの原則に反するダイナミクスを助長する危険性がある。企業の利益のために社会活動を搾取することを目的とした排他的で閉鎖的で不透明なプラットフォームは、社会生活のより多くの領域を占める非民主的な空間として機能しています。このモデルは、私たちが話している民主主義の新しいインフラとプロセスに関連して、特に危険です。

In the context of new configurations of informational capitalism (Castells, 1996), so-called “data capitalism" (Lohr, 2015; Morozov, 2015) or "surveillance capitalism" (Zuboff, 2015), the new digital infrastructures of democracy run the risk of contributing to dynamics contrary to such principles as privacy and technological sovereignty. Exclusive, closed and opaque platforms geared towards exploiting social activities for corporate profit are operating as non-democratic spaces occupying more and more areas of social life. This model is particularly dangerous in relation to the new infrastructures and processes of democracy that we are talking about.

排他的で企業的なインフラモデルと比較して、 decidim.barcelonaの開発がインスピレーションを得る必要があると考えるパブリック・コモンズモデルは、デザイン、所有権、管理が自由、オープン、参加型で、公共の労働者と市民（組織化されているかどうかに関わらず）の間で共有されるプラットフォームの開発に向けられています。このモデルでは、プラットフォームのコードだけでなく、その中で生成されたデータも、公共と共通の管理の論理に従って処理され、利用されます。政治的原則としてのコモンズの特徴である、あらゆるものを参加に向けて開放することは、参加型のインフラが完全に機能するための基本的な条件であるように思われます（私的領域や国家公共領域とは対照的に）。ここでは、参加は再帰的でなければなりません。参加は、それ自体が存在するインフラの条件を定義し、確立するのを助け、デジタル参加型プラットフォームの設計、開発、管理、そしてそこで生成されるプロセスや結果（データなど）に影響を与える必要があります。

Compared to the exclusive and corporate infrastructural model, the public commons model, which we believe decidim.barcelona’s development needs to be inspired by, ​​is geared towards developing platforms where design, ownership and management are free, open and participatory, shared between public workers and citizens (organised or not). Under this model, not only the platform's code but also the data that are generated in it are processed and appropriated according to the logic of public and common management. The opening-up of everything and anything to participation, the hallmark of the commons as a political principle (as opposed to the private and even state-public sphere --- Laval & Dardot, 2015), seems to be a basic condition for participatory infrastructures to be fully functional. Participation has to be recursive here: it needs to help to define and establish the infrastructural conditions of its own existence and to affect the design, development and management of digital participatory platforms as well as the processes and results (e.g. data) that are generated in them.

大規模なデジタルサービス企業の手に渡れば、社会生活のアルゴリズム的な組織化や、我々が関心を持っている分野である政治参加は、民主主義と技術的な主権にリスクをもたらし、デジタルインフラにおけるパブリック・コモンズの努力だけが逆転させることができます。より質の高い民主主義を構築するためには、無料、オープン、透明、安全、パブリック・コモンズ管理ソフトウェアに基づいたプラットフォームだけが保証を提供します。未来の民主主義は、民主的なインフラの上に構築されなければなりません。

Put in the hands of large digital-service corporations, the algorithmic organisation of social life and the area we are concerned with, political participation, poses a risk to democracy and technological sovereignty that only a public commons effort in digital infrastructures can reverse. Only platforms based on free, open, transparent, secure and public-commons management software offer guarantees when it comes to building democracies of greater quality. The democracy of the future has to be built, then, on democratic infrastructures.
